import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface DocumentPdfOptions {
  title: string;
  docNumber: string;
  status: string;
  createdAt: string;
  fields: Array<{ label: string; value: string }>;
  lineItems?: Array<Record<string, string | number>>;
  lineItemColumns?: string[];
  /** Optional signature lines (e.g. ['Prepared By', 'Approved By', 'Received By']) */
  signatures?: string[];
  /** Whether to open print dialog instead of saving */
  printMode?: boolean;
}

export function generateDocumentPdf(options: DocumentPdfOptions) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header - NIT branding
  doc.setFillColor(46, 49, 146); // nesma-primary
  doc.rect(0, 0, pageWidth, 40, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.text('NIT Logistics & WMS', 14, 18);
  doc.setFontSize(10);
  doc.text('Nesma Infrastructure & Technology', 14, 26);
  doc.text(options.title, 14, 34);

  // Document info
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.text(options.docNumber, 14, 52);

  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Status: ${options.status}`, pageWidth - 14, 52, { align: 'right' });
  doc.text(`Date: ${options.createdAt}`, pageWidth - 14, 58, { align: 'right' });

  // Fields section (two-column layout)
  let yPos = 68;
  doc.setFontSize(10);

  for (let i = 0; i < options.fields.length; i += 2) {
    const field1 = options.fields[i];
    const field2 = options.fields[i + 1];

    doc.setTextColor(100, 100, 100);
    doc.text(field1.label + ':', 14, yPos);
    doc.setTextColor(0, 0, 0);
    doc.text(String(field1.value || '-'), 70, yPos);

    if (field2) {
      doc.setTextColor(100, 100, 100);
      doc.text(field2.label + ':', pageWidth / 2 + 5, yPos);
      doc.setTextColor(0, 0, 0);
      doc.text(String(field2.value || '-'), pageWidth / 2 + 55, yPos);
    }

    yPos += 8;
  }

  // Line items table
  if (options.lineItems && options.lineItems.length > 0 && options.lineItemColumns) {
    yPos += 10;
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text('Line Items', 14, yPos);

    autoTable(doc, {
      startY: yPos + 5,
      head: [options.lineItemColumns],
      body: options.lineItems.map(item => options.lineItemColumns!.map(col => String(item[col] ?? ''))),
      theme: 'grid',
      headStyles: { fillColor: [46, 49, 146], textColor: 255 },
      styles: { fontSize: 9 },
    });
  }

  // Signature lines
  const signatures = options.signatures ?? getDefaultSignatures(options.title);
  if (signatures.length > 0) {
    // Get current Y position after autoTable or field section
    const finalY = (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? yPos;
    let sigY = finalY + 20;

    // Check if we need a new page for signatures
    const pageHeight = doc.internal.pageSize.getHeight();
    if (sigY + 40 > pageHeight - 20) {
      doc.addPage();
      sigY = 30;
    }

    const sigColWidth = (pageWidth - 28) / Math.min(signatures.length, 3);
    doc.setFontSize(9);

    signatures.forEach((label, i) => {
      const x = 14 + (i % 3) * sigColWidth;
      const rowY = sigY + Math.floor(i / 3) * 40;

      // Signature line
      doc.setDrawColor(180, 180, 180);
      doc.line(x, rowY + 20, x + sigColWidth - 10, rowY + 20);

      // Label
      doc.setTextColor(100, 100, 100);
      doc.text(label, x, rowY + 26);

      // Date line
      doc.setTextColor(180, 180, 180);
      doc.text('Date: _______________', x, rowY + 32);
    });
  }

  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 15;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by NIT Logistics & WMS', 14, footerY);
  doc.text(new Date().toLocaleString(), pageWidth - 14, footerY, { align: 'right' });

  // Print or Download
  if (options.printMode) {
    doc.autoPrint();
    window.open(doc.output('bloburl'), '_blank');
  } else {
    doc.save(`${options.docNumber}.pdf`);
  }
}

/** Default signature labels per document type */
function getDefaultSignatures(title: string): string[] {
  const lower = title.toLowerCase();
  if (lower.includes('receiving')) return ['Received By', 'Checked By (QC)', 'Warehouse Supervisor'];
  if (lower.includes('issue')) return ['Requested By', 'Approved By', 'Issued By'];
  if (lower.includes('return')) return ['Returned By', 'Received By', 'Warehouse Supervisor'];
  if (lower.includes('inspection')) return ['Inspector', 'QC Manager'];
  if (lower.includes('gate pass')) return ['Issued By', 'Security Officer'];
  if (lower.includes('job order')) return ['Requested By', 'Approved By', 'Contractor'];
  if (lower.includes('stock transfer')) return ['Requested By', 'Approved By', 'Shipped By', 'Received By'];
  return ['Prepared By', 'Approved By'];
}

export interface ReportPdfOptions {
  title: string;
  subtitle?: string;
  generatedAt?: string;
  filters?: Array<{ label: string; value: string }>;
  columns: string[];
  rows: Array<Record<string, string | number>>;
  summary?: Array<{ label: string; value: string | number }>;
}

export function generateReportPdf(options: ReportPdfOptions) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header - NIT branding
  doc.setFillColor(46, 49, 146);
  doc.rect(0, 0, pageWidth, 40, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.text('NIT Logistics & WMS', 14, 18);
  doc.setFontSize(10);
  doc.text('Nesma Infrastructure & Technology', 14, 26);
  doc.setFontSize(14);
  doc.text(options.title, 14, 36);

  let yPos = 50;

  // Subtitle + date
  doc.setTextColor(100, 100, 100);
  doc.setFontSize(10);
  if (options.subtitle) {
    doc.text(options.subtitle, 14, yPos);
    yPos += 6;
  }
  doc.text(`Generated: ${options.generatedAt || new Date().toLocaleString()}`, 14, yPos);
  yPos += 10;

  // Filters
  if (options.filters && options.filters.length > 0) {
    doc.setFontSize(9);
    doc.setTextColor(80, 80, 80);
    options.filters.forEach(f => {
      doc.text(`${f.label}: ${f.value}`, 14, yPos);
      yPos += 5;
    });
    yPos += 5;
  }

  // Summary cards
  if (options.summary && options.summary.length > 0) {
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    const colW = (pageWidth - 28) / Math.min(options.summary.length, 4);
    options.summary.forEach((s, i) => {
      const x = 14 + (i % 4) * colW;
      doc.setFontSize(8);
      doc.setTextColor(100, 100, 100);
      doc.text(s.label, x, yPos);
      doc.setFontSize(14);
      doc.setTextColor(0, 0, 0);
      doc.text(String(s.value), x, yPos + 6);
    });
    yPos += 16;
  }

  // Data table
  autoTable(doc, {
    startY: yPos,
    head: [options.columns],
    body: options.rows.map(row => options.columns.map(col => String(row[col] ?? ''))),
    theme: 'grid',
    headStyles: { fillColor: [46, 49, 146], textColor: 255 },
    styles: { fontSize: 8 },
  });

  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 15;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by NIT Logistics & WMS', 14, footerY);
  doc.text(new Date().toLocaleString(), pageWidth - 14, footerY, { align: 'right' });

  doc.save(`${options.title.replace(/\s+/g, '_')}_Report.pdf`);
}

/** Map a resource record to PDF options based on resource type */
export function buildPdfOptions(resourceType: string, record: Record<string, unknown>): DocumentPdfOptions {
  const docNumber = String(
    record.mrrvNumber ||
      record.mirvNumber ||
      record.mrvNumber ||
      record.joNumber ||
      record.rfimNumber ||
      record.osdNumber ||
      record.gatePassNumber ||
      record.transferNumber ||
      record.shipmentNumber ||
      record.id ||
      '',
  );
  const common = {
    docNumber,
    status: String(record.status || ''),
    createdAt: record.createdAt
      ? new Date(String(record.createdAt)).toLocaleDateString()
      : record.date
        ? String(record.date)
        : '',
  };

  switch (resourceType) {
    case 'mrrv':
      return {
        ...common,
        title: 'Goods Receipt Note',
        fields: [
          { label: 'Supplier', value: String((record as Record<string, unknown>).supplier || record.supplierId || '') },
          {
            label: 'Warehouse',
            value: String((record as Record<string, unknown>).warehouse || record.warehouseId || ''),
          },
          { label: 'Project', value: String((record as Record<string, unknown>).project || record.projectId || '') },
          { label: 'PO Reference', value: String(record.poReference || record.poNumber || '') },
          { label: 'Delivery Note', value: String(record.deliveryNoteNumber || '') },
          { label: 'Total Value', value: record.value ? `${Number(record.value).toLocaleString()} SAR` : '-' },
          { label: 'Notes', value: String(record.notes || '') },
        ],
      };
    case 'mirv':
      return {
        ...common,
        title: 'Material Issuance',
        fields: [
          { label: 'Project', value: String(record.project || record.projectId || '') },
          { label: 'Requester', value: String(record.requester || record.requesterId || '') },
          { label: 'Warehouse', value: String(record.warehouse || record.warehouseId || '') },
          { label: 'Total Value', value: record.value ? `${Number(record.value).toLocaleString()} SAR` : '-' },
          { label: 'Notes', value: String(record.notes || '') },
        ],
      };
    case 'mrv':
      return {
        ...common,
        title: 'Material Return Note',
        fields: [
          { label: 'Return Type', value: String(record.returnType || '') },
          { label: 'Project', value: String(record.project || record.projectId || '') },
          { label: 'Warehouse', value: String(record.warehouse || record.warehouseId || '') },
          { label: 'Notes', value: String(record.notes || '') },
        ],
      };
    case 'job-orders':
      return {
        ...common,
        title: 'Job Order',
        fields: [
          { label: 'Type', value: String(record.type || '') },
          { label: 'Project', value: String(record.project || record.projectId || '') },
          { label: 'Requester', value: String(record.requester || record.requesterId || '') },
          { label: 'Vehicle', value: String(record.vehicle || '') },
          { label: 'Driver', value: String(record.driver || '') },
          { label: 'SLA Status', value: String(record.slaStatus || '') },
          { label: 'Notes', value: String(record.notes || '') },
        ],
      };
    case 'rfim':
      return {
        ...common,
        title: 'Quality Control Inspection',
        fields: [
          { label: 'GRN ID', value: String(record.mrrvId || '') },
          { label: 'Inspection Type', value: String(record.inspectionType || '') },
          { label: 'Priority', value: String(record.priority || '') },
          { label: 'Inspector', value: String(record.inspector || '') },
          { label: 'Result', value: String(record.result || record.status || '') },
          { label: 'Notes', value: String(record.notes || '') },
        ],
      };
    case 'osd':
      return {
        ...common,
        title: 'Discrepancy Report',
        fields: [
          { label: 'GRN ID', value: String(record.mrrvId || '') },
          { label: 'Report Type', value: String(record.reportType || '') },
          { label: 'Qty Affected', value: String(record.qtyAffected || '') },
          { label: 'Action Required', value: String(record.actionRequired || '') },
          { label: 'Notes', value: String(record.notes || '') },
        ],
      };
    case 'gate-pass':
      return {
        ...common,
        title: 'Gate Pass',
        fields: [
          { label: 'Type', value: String(record.type || '') },
          { label: 'Linked Document', value: String(record.linkedDocument || '') },
          { label: 'Warehouse', value: String(record.warehouse || '') },
          { label: 'Vehicle Plate', value: String(record.vehiclePlate || '') },
        ],
      };
    case 'stock-transfer':
      return {
        ...common,
        title: 'Stock Transfer',
        fields: [
          { label: 'From Warehouse', value: String(record.fromWarehouse || '') },
          { label: 'To Warehouse', value: String(record.toWarehouse || '') },
          { label: 'Notes', value: String(record.notes || '') },
        ],
      };
    case 'shipments':
      return {
        ...common,
        title: 'Shipment',
        fields: [
          { label: 'Supplier', value: String(record.supplier || '') },
          { label: 'Description', value: String(record.description || '') },
          { label: 'ETD', value: String(record.etd || '') },
          { label: 'ETA', value: String(record.eta || '') },
          { label: 'Port', value: String(record.port || '') },
          { label: 'Agent', value: String(record.agent || '') },
        ],
      };
    default:
      return {
        ...common,
        title: resourceType.toUpperCase(),
        fields: Object.entries(record)
          .filter(([k]) => !['id', 'createdAt', 'updatedAt'].includes(k))
          .slice(0, 10)
          .map(([k, v]) => ({ label: k, value: String(v ?? '') })),
      };
  }
}
