import React from 'react';
import { Printer } from 'lucide-react';

interface PrintableDocumentProps {
  title: string;
  documentNumber?: string;
  children: React.ReactNode;
}

/**
 * Wrapper component for print-optimized document views.
 * Includes NIT header, @media print styles, and a print trigger button.
 *
 * Everything inside this wrapper renders with white background and black text when printed.
 * Non-print elements (like the print button) are hidden via the `no-print` class.
 */
export const PrintableDocument: React.FC<PrintableDocumentProps> = ({ title, documentNumber, children }) => {
  return (
    <>
      {/* Print styles injected once */}
      <style>{`
        @media print {
          /* Hide everything except the printable area */
          body > *:not(#print-root) {
            display: none !important;
          }
          /* Reset the printable area to clean white background */
          .printable-document {
            background: white !important;
            color: black !important;
            padding: 0 !important;
            margin: 0 !important;
            border: none !important;
            box-shadow: none !important;
          }
          .printable-document * {
            color: black !important;
            background: transparent !important;
            border-color: #ddd !important;
          }
          .printable-document .print-header {
            border-bottom: 2px solid #1e3a5f !important;
            padding-bottom: 12px !important;
            margin-bottom: 16px !important;
          }
          .printable-document .print-header h1 {
            color: #1e3a5f !important;
          }
          .printable-document .print-header .print-subtitle {
            color: #c5a572 !important;
          }
          .no-print {
            display: none !important;
          }
          /* Page break handling */
          .page-break {
            page-break-before: always;
          }
          table {
            page-break-inside: auto;
          }
          tr {
            page-break-inside: avoid;
          }
        }
      `}</style>

      <div className="printable-document">
        {/* NIT letterhead header for print */}
        <div className="print-header hidden print:block mb-6 pb-4 border-b-2 border-[#1e3a5f]">
          <div className="flex justify-between items-start">
            <div>
              <h1 className="text-xl font-bold" style={{ color: '#1e3a5f' }}>
                NIT Supply Chain Management
              </h1>
              <p className="print-subtitle text-sm font-medium mt-1" style={{ color: '#c5a572' }}>
                {title}
              </p>
            </div>
            <div className="text-right text-sm">
              {documentNumber && <p>Doc #: {documentNumber}</p>}
              <p>{new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })}</p>
            </div>
          </div>
        </div>

        {/* Print button (screen only) */}
        <div className="no-print flex justify-end mb-4">
          <button
            onClick={() => window.print()}
            className="flex items-center gap-2 px-4 py-2 bg-white/5 border border-white/10 rounded-xl text-sm font-medium text-gray-300 hover:text-white hover:bg-white/10 hover:border-white/20 transition-all"
          >
            <Printer size={16} />
            Print
          </button>
        </div>

        {/* Document content */}
        {children}

        {/* Print footer */}
        <div className="hidden print:block mt-8 pt-4 border-t border-gray-300 text-xs text-gray-500 flex justify-between">
          <span>Generated by NIT SCS V2</span>
          <span>{new Date().toLocaleDateString('en-GB')}</span>
        </div>
      </div>
    </>
  );
};
